Downgraded com.unity.xr.openxr to version 1.8.1. Version 1.8.2 introduces an unresolved dependency to UnityEngine.UnityAnalyticsModule. Error message:
Library\PackageCache\com.unity.xr.openxr@1.8.2\Runtime\OpenXRAnalytics.cs(136,13): error CS0012: The type 'AnalyticsResult' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.